### ISSUE TITLE
Pressing Volume Down media key brings you to Level Completion

### ISSUE THREAD

**Issue by HayleeIHatton** [CosmicBagel/LOTE-issues#7]
**Describe the bug**
When I pressed F5 to lower the volume within the playing levels it brought me to the Level complete screen. This happened on every level until you reach game completion at the end (where it shows the credits). 

**To Reproduce**
Steps to reproduce the behavior.
This is a step-by-step process on how to recreate the video uploaded. 
In summary, press F5 during gameplay (within the level/wave), and you will be directed to the completion screen. 

**Expected behavior**
When I press F5 on my laptop I would have expected the game volume to go down and that's it (an alternative to pressing down on the mechanical volume button on the computer)
![image](https://user-images.githubusercontent.com/85526580/129080705-47df17ee-2786-49ac-ab5f-91403c82eee8.png)

**Visuals**
Link to download the video here: 
https://drive.google.com/file/d/1AgRFfq6Y-NEAbLiMngM-sNQdMd_NHzKu/view?usp=sharing

**Platform and Version (please complete the following information):**
 - OS: Windows 
 - Browser: Google Chrome 
 - Browser Version: Version 92.0.4515.131 (Official Build) (64-bit)
 - Game Version:   0.3.12

**Additional context**

**Comment by CosmicBagel** [comment]
Okay so its any time you use a media key to turn down volume.

If you don't have volume controls on your keyboard you can recreate this using AutoHotKey and binding `Volume_Down` to a key
eg `1::Volume_Down`

Then anytime you press the 1 key, the level will be completed.

**Comment by CosmicBagel** [comment]
Marking as medium priority as this is a common action users will do while playing the game.

**Comment by CosmicBagel** [comment]
This is one of the dev cheat hotkeys, we'll make them editor only via a pre-processor so they don't get into these real builds

**Comment by CosmicBagel** [comment]
Confirmed, this ONLY occurs in the webgl version of the game, not the desktop version

**Comment by CosmicBagel** [comment]
Does NOT occur in firefox
